###############################################################################################
# Module manifest for module 'EducateIT.PSFunctions'
#
# Generated by: EducateIT GmbH
# 
#
# Copyright	:	(c)2025 by EducateIT GmbH - http://educateit.ch - info@educateit.ch
#
# History:
#           V1.3.0.0 - 16.03.2020 - M. Trojahn - Remove Test-Port in ScriptFunctions.ps1
#           V1.4.0.0 - 17.06.2020 - M. Trojahn - Add VHDFunctions
#                      12.08.2020 - M. Trojahn - AddDriveFunctions, FSLogixFunctions
#           V1.5.0.0 - 14.12.2020 - M. Trojahn - Add LogFunctions, fix error in MessageFunctions & ADFunctiions
#           V1.6.0.0 - 06.04.2021 - M. Trojahn - Add EducateITStatisticServerFunctions
#          		   	   07.04.2021 - M. Trojahn - Update ADFunctions (Get-EitBitlockerPasswords)
#           V1.7.0.0 - 07.11.2021 - M. Trojahn - rename EducateITServerVersions.ps1 to EducateITServerInformation.ps1
#					     						 add Get-EitServerServiceInfo
#           V1.7.3.0 - 17.11.2021 - M. Trojahn - Add Name parameter, required for reporting in Get-EitServerServiceInfo
#           V1.8.0.0 - 14.03.2022 - M. Trojahn - Rename Invoke-EitExecutable to Start-EitExecutable in SetupFunctions.ps1 because of Trend ApexOne Behavior Monitoring
#           V1.8.1.0 - 27.04.2022 - M. Trojahn - Add log to Send-EitNetMessage function in MessageFunctions.ps1
#           V1.8.2.0 - 03.08.2022 - M. Trojahn - Add New-EitEncryptedPassword function in ScriptFunctions.ps1
#           V1.9.0.0 - 27.10.2022 - M. Trojahn - Add CitrixDaaSFunctions.ps1
#           V1.9.1.0 - 01.11.2022 - M. Trojahn - ProcessMonitorFunctions.ps1
#			V1.9.2.0 - 21.12.2022 - M. Trojahn - Remove MaxRecordCount from Stop-EitBrokerSession in CitrixFunctions.ps1
#			V1.9.3.0 - 20.03.2023 - M. Trojahn - add Get-EitPSUnique in ScriptFunctions.ps1
#												add Get-EitBrokerMachine in CitrixFunctions.ps1	
#			V1.9.4.0 - 29.03.2023 - M. Trojahn - add Get-EitADUser in ADFunctions.ps1
#			V1.9.5.0 - 13.04.2023 - M. Trojahn - add Get-EitBrokerSessions, Stop-EitAllBrokerSessionOnMachine in CitrixFunctions.ps1
#												add New-EitLogger in LogFunctions.ps1
#												Test also for the new raptor server path in Get-EitRemoteComputersFromXenDataConf
#									 			Add Get-EitLinkNamesFromXenDataConf, Get-EitLinkNameForBrokerMachine in ScriptFunctions.ps1
#			V1.9.6.0 - 07.09.2023 - M. Trojahn - Add UTF8 Encoding in function New-EitEncryptedPassword in ScriptFunctions.ps1
#			V1.9.7.0 - 11.09.2023 - M. Trojahn - Add UseBasicParsing in function Get-EitCitrixDaaSbearerToken in CitrixDaaSFunctions.ps1
#			V1.9.8.0 - 12.12.2023 - M. Trojahn - Add logger to stop-eitbrokersession, only use remoting if it is required in Get-EitServerServiceInfo
#					   20.12.2023 - M. Trojahn - Add add full site data to Get-EitSiteInfo
#			V2.0.0.0 - 18.03.2023 - M. Trojahn - Add RDSFunctions.ps1 (Get-EitWTSSessionId & Get-EitWTSSessionInformation) 
#			V2.0.1.0 - 09.04.2024 - M. Trojahn - return $FileIsLocked = $false if file does not exists in function Test-EITFileIsLocked in VHDFunctions.ps1
#			V2.0.2.0 - 19.04.2024 - M. Trojahn - fix wrong client_id & client_secret variable declaration in function Get-EitCitrixDaaSbearerToken in CitrixDaaSFunctions.ps1
#			V2.0.3.0 - 22.05.2024 - M. Trojahn - check if $OSType = $null in Get-EitBrokerMachines in CitrixFunctiond
#			V2.1.0.0 - 03.09.2024 - M. Trojahn - Add MSAvDFunctions.ps1 (Get-EitAzBearerToken, Get-EitAzHostPoolsBySubscription, 
#							                     Get-EitAzSessionHostsByHostPool, Get-EitAzUserSessionsByHostPool, Send-EitAzUserMessage, 
#												 Disconnect-EitAzUserSession, Remove-EitAzUserSession)
#			V2.2.0.0 - 26.09.2024 - M. Trojahn - Add CertificateFunctions.ps1
#			V2.2.1.0 - 03.10.2024 - M. Trojahn - CitrixFunctions.ps1: Error check if Machine not found in ProvisioningSchemeName in Function Remove-EitProvVM,
#  												  Return success even if ProvVM doesn't exists in Get-EitCitrixMachineInfo
#  												  add more information: ProvVM, AcctADAccount & BrokerMachine in Function Get-EitCitrixMachineInfo
#												  do some code style cleanup
#			V2.2.2.0 - 05.12.2024 - M. Trojahn - CitrixFunctions.ps1: add function Get-EitBrokerSession, Stop-BrokerSession2
#			V2.2.3.0 - 06.01.2025 - M. Trojahn - CertificatesFunctions.ps1: add add Invoke-EitOpenSSLCommand & Convert-EitPfxFile 
#												 modify New-EitCACertificate, New-EitCertificateSigningRequest &  New-EitSelfSignedCertificate to use Invoke-EitOpenSSLCommand
#												 Code optimizations
#			V2.2.4.0 - 25.02.2025 - M. Trojahn - add CitrixCVADFunctions.ps1, adds Get-EitCitrixCVADMe, Get-EitCitrixCVADSessionsInSite, Get-EitCitrixCVADSMachinesInSite, Get-EitCitrixCVADbearerToken
#												 optimize Get-EitBrokerSessions in CitrixFunctions.ps1
#			V2.2.5.0 - 06.03.2005 - M. Trojahn - Add UserName & MachineName parameter in function Get-EitCitrixCVADSessions in CitrixCVADFunctions.ps1		
#			V2.2.5.1 - 18.08.2005 - M. Trojahn - adding Force Parameter in Remove-EitAzUserSession in MSAvDFunctions.ps1
#
#			V3.0.0.0 - 05.09.2005 - M. Trojahn - Restructured for use with Pester unit tests.
#			V3.0.1.0 - 16.10.2005 - M. Trojahn - Go back to log4net 2.0.15 because 3.0 isn't compatible
#			V3.0.2.0 - 17.10.2005 - M. Trojahn - use again log4net 3.2
#												 remove function New-FileEitLogger because it doesn't work with log4net 3.2
#												 add alias New-FileEitLogger to New-EitLogger to ensure backwards compatibility
#												 add LogFunctions.Tests.ps1
#			V3.0.3.0 - 19.01.2026 - M. Trojahn - Remove log4net.dll and use our own logging function.
#			V3.0.3.1 - 11.02.2026 - M. Trojahn - Create the log path if it does not exist in LogFunctions.
#
###############################################################################################

@{

	# Script module or binary module file associated with this manifest.
	# RootModule = ''

	# Version number of this module.
	ModuleVersion = '3.0.3.1'

	# Supported PSEditions
	# CompatiblePSEditions = @()

	# ID used to uniquely identify this module
	GUID = '8f46b42d-aec9-4b41-b8a3-f59ad56ee44e'

	# Author of this module
	Author = 'EducateIT GmbH'

	# Company or vendor of this module
	CompanyName = 'EducateIT GmbH'

	# Copyright statement for this module
	Copyright = '(c) 2026 EducateIT GmbH. All rights reserved.'

	# Description of the functionality provided by this module
	Description = 'EducateIT Powershell functions'


	# Minimum version of the Windows PowerShell engine required by this module
	# PowerShellVersion = ''

	# Name of the Windows PowerShell host required by this module
	# PowerShellHostName = ''

	# Minimum version of the Windows PowerShell host required by this module
	# PowerShellHostVersion = ''

	# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
	# DotNetFrameworkVersion = ''

	# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
	# CLRVersion = ''

	# Processor architecture (None, X86, Amd64) required by this module
	# ProcessorArchitecture = ''

	# Modules that must be imported into the global environment prior to importing this module
	# RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	# RequiredAssemblies = @()

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	# ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	# FormatsToProcess = @()

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	NestedModules = @(
		'.\public\ADFunctions.ps1', 
		'.\public\CitrixFunctions.ps1', 
		'.\public\MessageFunctions.ps1', 
		'.\public\XenDesktopFunctions.ps1',
		'.\public\ScriptFunctions.ps1',
		'.\public\EducateITServerInformation.ps1',
		'.\public\VHDFunctions.ps1',
		'.\public\DriveFunctions.ps1',
		'.\public\FSLogixFunctions.ps1',
		'.\public\LogFunctions.ps1',
		'.\public\SetupFunctions.ps1',
		'.\public\EducateITStatisticServerFunctions.ps1'
		'.\public\CitrixDaaSFunctions.ps1',
		'.\public\ProcessMonitorFunctions.ps1',
		'.\public\RDSFunctions.ps1',
		'.\public\MSAvDFunctions.ps1'
		'.\public\CertificateFunctions.ps1',
		'.\public\CitrixCVADFunctions.ps1'
	)

	# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport = @('*')

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport = @()

	# Variables to export from this module
	VariablesToExport = '*'

	# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
	AliasesToExport = @()

	# DSC resources to export from this module
	# DscResourcesToExport = @()

	# List of all modules packaged with this module
	# ModuleList = @()

	# List of all files packaged with this module
	# FileList = @()

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{
		PSData = @{
			# Tags applied to this module. These help with module discovery in online galleries.
			# Tags = @()

			# A URL to the license for this module.
			# LicenseUri = ''

			# A URL to the main website for this project.
			# ProjectUri = ''

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			# ReleaseNotes = ''

		} # End of PSData hashtable

	} # End of PrivateData hashtable

	# HelpInfo URI of this module
	# HelpInfoURI = ''

	# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
	# DefaultCommandPrefix = ''
}




