###############################################################################################
# script module for module 'EducateIT.PSFunctions'
#
# Generated by: EducateIT GmbH
# 
#
# Copyright	:	(c)2025 by EducateIT GmbH - http://educateit.ch - info@educateit.ch
#
# History:
#           V3.0.0.0 - 05.09.2025 - M. Trojahn - initial creation
#
#
#
###############################################################################################

# Import all the functions from the public folder.
Get-ChildItem -Path "$PSScriptRoot\Public\*.ps1" | ForEach-Object {
	write-host $_.FullName
    . $_.FullName
}